import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider as NextThemesProvider } from "next-themes"
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/components/ui/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Immi Application",
  description: "Generated by Immi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`w-screen h-screen ${inter.className}`}>
      <NextThemesProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Providers>
            <main className="h-full">
              {children}
            </main>
          </Providers>
      </NextThemesProvider>
      </body>
    </html>
  );
}