import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/components/providers";
import { Suspense } from "react";
import { ProgressBar } from '@lexz451/next-nprogress';
import SonnerTest from "@/components/sonnerTest";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Immi Application",
  description: "Generated by Immi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark customScrollBar">
      <body className={`w-screen h-screen customScrollBar ${inter.className}`}>
        <NextThemesProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={true}>
            <ProgressBar
              // color={config.BrandColor}
              height="2px"
              options={{
                showSpinner: false,
              }}
            />
          </Suspense>
          <Providers>
            <main className="h-full">
              {children}
            {/* <SonnerTest /> */}
            </main>
          </Providers>
        </NextThemesProvider>
      </body>
    </html>
  );
}
